# Generated by Django 2.2.4 on 2019-08-22 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190821_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
