# Generated by Django 2.2.4 on 2019-08-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cv_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='file',
        ),
    ]
