# Generated by Django 2.2.4 on 2019-08-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190822_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_image_one',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_image_two',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
