# Generated by Django 2.2.4 on 2019-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images')),
                ('category', models.CharField(choices=[('All', 'All'), ('upcoming', 'upcomming'), ('following', 'following'), ('latest', 'latest')], max_length=20)),
            ],
        ),
    ]
