# Generated by Django 2.2.4 on 2019-09-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('upcoming', 'upcoming'), ('following', 'following'), ('latest', 'latest')], max_length=20),
        ),
    ]
